/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/9.7.1/userguide/multi_project_builds.html in the Gradle documentation.
 */

plugins {
    id("io.github.ben-manes.versions.settings") version "0.61.0"
}

rootProject.name = "sykmelding-ocr"
include("lib")
include("template")