/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin library project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.7.1/userguide/building_java_projects.html in the Gradle documentation.
 */
val javacppVersion = "1.5.14"
val opencv = "4.14.0-1.5.14$javacppVersion"
version = file("./version").readText().trim()
plugins {
    // Apply the org.jetbrains.kotlin.jvm Plugin to add support for Kotlin.
    alias(libs.plugins.kotlin.jvm)
    id("maven-publish")

    // Apply the java-library plugin for API and implementation separation.
    `java-library`
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use the Kotlin Test integration.
    testImplementation("org.jetbrains.kotlin:kotlin-test")

    // Use the JUnit 5 integration.
    testImplementation(libs.junit.jupiter.engine)

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
    testImplementation("org.apache.pdfbox:pdfbox:3.0.8")
    // This dependency is exported to consumers, that is to say found on their compile classpath.
    api(libs.commons.math3)
    implementation(libs.bytedeco.tesseract)
    implementation(libs.bytedeco.tesseract.platform)
    implementation(libs.bytedeco.javacv)
    // This dependency is used internally, and not exposed to consumers on their own compile classpath.
    implementation(libs.guava)
    implementation(libs.jackson.module.kotlin)
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}

publishing {
    publications {
        create<MavenPublication>("gpr") {
            from(components["java"])
            groupId = "no.nav.tsm"
            artifactId = "sykmelding-ocr"
            version = version
        }
    }
     repositories {
         maven {
             name = "GitHubPackages"
             url = uri("https://maven.pkg.github.com/navikt/sykmelding-ocr")
             credentials {
                 username = "x-access-token"
                 password = System.getenv("GITHUB_TOKEN")
             }
         }
     }
}